---
# Other
github-actions:
  - changed-files:
      - any-glob-to-any-file: ".github/**"
docker:
  - changed-files:
      - any-glob-to-any-file: "containers/**"
helm:
  - changed-files:
      - any-glob-to-any-file: "helm/**"