---
# Environment
- name: production
  color: "ee0701"
- name: staging
  color: "f9fb04"

# Categories
- name: github-actions
  color: "5319e7"
- name: docker
  color: "5319e7"
- name: helm
  color: "5319e7"

# release-please
- name: "autorelease: pending"
  color: "7bd3ea"