
apiVersion: v2
name: openebs
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 0.0.0

dependencies:
  - name: openebs
    repository: https://openebs.github.io/openebs
    version: 4.3.3