apiVersion: v2
name: k6-operator
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.1.0"

dependencies:
  - name: k6-operator
    repository: https://grafana.github.io/helm-charts
    version: 4.0.0
