---
{{- range $name, $instance := .Values.instances }}
{{- if $instance.enabled }}
  {{- $instanceValues := mergeOverwrite (deepCopy $.Values) $instance -}}
  {{- $global := dict
        "nameOverride" $name
  -}}
  {{- $_ := set $instanceValues "global" (merge $global (get $instanceValues "global" | default dict)) -}}
  {{- $ctx := dict
        "Values" $instanceValues
        "Release" $.Release
        "Chart" $.Chart
        "Subcharts" $.Subcharts 
        "Capabilities" $.Capabilities
  -}}
  {{- include "common.loader.all" $ctx }}
{{- end }}
{{- end }}