{{ if .Values.objectStore.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: {{ printf "%s-cluster-backup" .Release.Name | default "cloudnative-pg-cluster-backup" }}
spec:
  cluster:
    name: {{ printf "%s-cluster" .Release.Name | default "cloudnative-pg-cluster" }}
  schedule: {{ .Values.objectStore.schedule | default "0 0 0 * * *" }}
  backupOwnerReference: self
  immediate: true
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
{{ end }}