{{ if .Values.objectStore.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.s3secretName | default "minio" }}
spec:
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    creationPolicy: Owner
  dataFrom:
    - extract:
        key:  {{ .Values.s3secretName | default "minio" }}
{{ end }}