name: "Renovate: Dry-run"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/renovate.json5"
      - ".github/renovate/**.json5"
  
jobs:
  dry-run:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIV_KEY }}"

      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Verify Renovate Configuration
        uses: suzuki-shunsuke/github-action-renovate-config-validator@c22827f47f4f4a5364bdba19e1fe36907ef1318e # v1.1.1

      - name: Renovate
        uses: renovatebot/github-action@70ea19f1b0dc8a9cc7af1b4278f8d3fd9778b577 # v43.0.17@v34.147.0
        with:
          configurationFile: .github/renovate.json5
          token: '${{ steps.app-token.outputs.token }}'
        env:
          LOG_LEVEL: debug
          RENOVATE_HOST_RULES: '[{"hostType": "docker", "domainName": "ghcr.io", "username": "${{ secrets.CI_BOT_USERNAME }}","password": "${{ secrets.CI_BOT_TOKEN }}"}]'
          # https://docs.renovatebot.com/configuration-options/#mode
          RENOVATE_MODE: silent